### ISSUE TITLE
Jenkinsfile Modification: Unexpected End-of-Comment Behavior

### ISSUE THREAD

**Issue by gounthar** [jenkins-infra/plugin-modernizer-tool#371] opened 2024-11-06 16:47 UTC
When running the `AddOrModernizeJenkinsFile` recipe, the generated comment does not create a new line. As a result, the subsequent `buildPlugin` statement is appended to the comment, rather than starting on a new line.

You can see this issue in [this pull request](https://github.com/jenkinsci/configurationslicing-plugin/pull/295/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8R4).

## Reproduction Steps
1. Run the `AddOrModernizeJenkinsFile` recipe on a plugin with an outdated Jenkinsfile.

## Expected Behavior
The recipe should add a new line and carriage return after the comment.

## Actual Behavior
The comment does not create a new line, and the `buildPlugin` statement is appended to it.

**Comment by jonesbusy** [comment] 2024-11-06 16:52
Is it and issue with plugin modernizer or rewrite-jenkins ? From wat I remember we don't modify and Jenkinsfile here but just use a recipe from rewrite-jenkins

**Comment by jonesbusy** [comment] 2024-11-06 16:55
Or even with rewite-groovy that fail to parse a correct LST ?

**Comment by gounthar** [comment] 2024-11-06 16:55
Yes, that's also what I think, but I prefer to have it logged here before forgetting about it.

**Comment by gounthar** [comment] 2024-11-06 17:57
What is strange is that the newline is in the [OpenRewrite recipe](https://github.com/openrewrite/rewrite-jenkins/blob/d692400029543a609113293c6ee7e95f49b9fd6b/src/main/resources/META-INF/rewrite/rewrite.yml#L70).

**Comment by jonesbusy** [comment] 2024-12-29 04:52
This is an issue with the groovy parser.

Rewrite-jenkins do a wrong assertion

https://github.com/openrewrite/rewrite-jenkins/blob/a53f97d154aaf26b85cfb771bf80bc4fae767701/src/test/java/org/openrewrite/jenkins/ModernizeJenkinsfileTest.java#L109

We will need to fix it before doing other Jenkinsfile modification. For the moment we just need to add the file if missing

**Comment by jonesbusy** [comment] 2024-12-31 05:33
Possible fix by https://github.com/openrewrite/rewrite-jenkins/pull/85

I'v tested the use case on rewrite groovy. Was not able to reproduce the issue

At the end was only because the YAML block was trimming empty line when creating the text file

**Comment by jonesbusy** [comment] 2024-12-31 05:36
That's why https://github.com/jenkins-infra/plugin-modernizer-tool/pull/524/files didn't show the issue

I would suggest we use exclusively this even if `overwriteExisting: false` I would prefer we are not harmless for the moment and don't override the file until we are able to parse it and perform modification to it

This is tracked by https://github.com/jenkins-infra/plugin-modernizer-tool/issues/531

Closing the issue then

**Closed by jonesbusy** 2024-12-31 05:36 UTC
